### ISSUE TITLE
Auth Exception after upgrade from M6 to M7 - "An Authentication object was not found in the SecurityContext"

### ISSUE THREAD

**Issue by mdymov-hayward** [eclipse/hawkbit#1171]
Have a properly running docker image with M6 release of Hawkbit using RabbitMQ and MySQL as data backend. 

Upgraded to M7 by doing the following:

- changed all hawkbit version references from M6 to M7 in `pom.xml`;
- changed the code in `src/main/java/org/eclipse/hawkbit/app/MyUI.java` to account for additional parameter `final UIEventProvider eventProvider` added in M7;
- changed  hawkbit version references from M6 to M7 in `Dockerfile`.

The docker image builds and the container starts. RabbitMQ and MySQL containers are also running. The Hawkbit UI comes up and I can log into the Hawkbit. The device data and distribution sets information is shown on the page initially.

However when I try to look at any particular devices or distribution set data (clicking on the line) the Hawkbit UI displays error about not finding the Auth object in Security Context. If I continue trying then the errors get more detailed (will be shown below), and when other tabs on the left are accessed there is "access denied" error on UI.

Here is the log of Initial startup and first error:

```
hawkbit-01_1  |      JAVA_OPTIONS: -Xss300K -Xms1g -Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=250m -XX:MaxMetaspaceSize=250m
hawkbit-01_1  | ******************************************************************
hawkbit-01_1  | 
hawkbit-01_1  |   .   ____          _            __ _ _
hawkbit-01_1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
hawkbit-01_1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
hawkbit-01_1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
hawkbit-01_1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
hawkbit-01_1  |  =========|_|==============|___/=/_/_/_/
hawkbit-01_1  |  :: Spring Boot ::        (v2.3.7.RELEASE)
hawkbit-01_1  | 

hawkbit-01_1  | 2021-08-27 19:48:31.128  INFO 1 --- [           main] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
hawkbit-01_1  | 2021-08-27 19:48:31.154  INFO 1 --- [           main] o.s.web.servlet.DispatcherServlet        : Completed initialization in 20 ms

hawkbit-01_1  | 2021-08-27 19:50:04.470 ERROR 1 --- [tp1151512955-21] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI: 
hawkbit-01_1  | 
hawkbit-01_1  | org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
hawkbit-01_1  | 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
hawkbit-01_1  | 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:223)
hawkbit-01_1  | 	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:156)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
hawkbit-01_1  | 	at org.eclipse.hawkbit.repository.jpa.JpaTargetManagement$$EnhancerBySpringCGLIB$$2a46826.getControllerAttributes(<generated>)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.management.targettable.TargetDetails.lambda$buildAttributesLayout$36f7b166$1(TargetDetails.java:129)
hawkbit-01_1  | 	at com.vaadin.data.Binder$BindingImpl.initFieldValue(Binder.java:1234)
hawkbit-01_1  | 	at com.vaadin.data.Binder$BindingImpl.access$100(Binder.java:1070)
hawkbit-01_1  | 	at com.vaadin.data.Binder.lambda$setBean$1(Binder.java:1807)
hawkbit-01_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1259)
hawkbit-01_1  | 	at com.vaadin.data.Binder.setBean(Binder.java:1807)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.detailslayout.AbstractGridDetailsLayout.masterEntityChanged(AbstractGridDetailsLayout.java:174)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.management.targettable.TargetDetails.masterEntityChanged(TargetDetails.java:201)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.management.targettable.TargetDetails.masterEntityChanged(TargetDetails.java:43)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.layout.listener.SelectionChangedListener.lambda$onSelectionChanged$0(SelectionChangedListener.java:70)
hawkbit-01_1  | 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
hawkbit-01_1  | 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
hawkbit-01_1  | 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
hawkbit-01_1  | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
hawkbit-01_1  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
hawkbit-01_1  | 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
hawkbit-01_1  | 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
hawkbit-01_1  | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
hawkbit-01_1  | 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.layout.listener.SelectionChangedListener.onSelectionChanged(SelectionChangedListener.java:70)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.layout.listener.SelectionChangedListener.onSelectionChangedEvent(SelectionChangedListener.java:58)
hawkbit-01_1  | 	at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
hawkbit-01_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hawkbit-01_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
hawkbit-01_1  | 	at org.vaadin.spring.events.internal.MethodListenerWrapper.publish(MethodListenerWrapper.java:78)
hawkbit-01_1  | 	at org.vaadin.spring.events.internal.ListenerCollection.publish(ListenerCollection.java:167)
hawkbit-01_1  | 	at org.vaadin.spring.events.internal.ScopedEventBus.publish(ScopedEventBus.java:116)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.grid.support.SelectionSupport.sendSelectionChangedEvent(SelectionSupport.java:154)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.grid.support.SelectionSupport.lambda$enableMultiSelection$253c84fa$1(SelectionSupport.java:179)
hawkbit-01_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
hawkbit-01_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
hawkbit-01_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hawkbit-01_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
hawkbit-01_1  | 	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
hawkbit-01_1  | 	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
hawkbit-01_1  | 	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
hawkbit-01_1  | 	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
hawkbit-01_1  | 	at com.vaadin.ui.components.grid.MultiSelectionModelImpl.doUpdateSelection(MultiSelectionModelImpl.java:483)
hawkbit-01_1  | 	at com.vaadin.ui.components.grid.MultiSelectionModelImpl.updateSelection(MultiSelectionModelImpl.java:455)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.grid.selection.RangeSelectionModel.updateSelection(RangeSelectionModel.java:66)
hawkbit-01_1  | 	at com.vaadin.ui.components.grid.MultiSelectionModelImpl$GridMultiSelectServerRpcImpl.select(MultiSelectionModelImpl.java:66)
hawkbit-01_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
hawkbit-01_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
hawkbit-01_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hawkbit-01_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
hawkbit-01_1  | 	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
hawkbit-01_1  | 	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
hawkbit-01_1  | 	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
hawkbit-01_1  | 	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
hawkbit-01_1  | 	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:149)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:247)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:550)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
hawkbit-01_1  | 	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
hawkbit-01_1  | 	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
hawkbit-01_1  | 	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
hawkbit-01_1  | 	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345)
hawkbit-01_1  | 	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:448)
hawkbit-01_1  | 	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272)
hawkbit-01_1  | 	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.jsr356.messages.TextWholeMessage.messageComplete(TextWholeMessage.java:59)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrEndpointEventDriver.onTextFrame(JsrEndpointEventDriver.java:228)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:152)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:326)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:148)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:113)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:168)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:92)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:202)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:225)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:259)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:459)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:440)
hawkbit-01_1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
hawkbit-01_1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
hawkbit-01_1  | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
hawkbit-01_1  | 	at java.lang.Thread.run(Thread.java:748)
hawkbit-01_1  | 
hawkbit-01_1  | 2021-08-27 19:50:04.498 ERROR 1 --- [tp1151512955-21] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI: 
hawkbit-01_1  | 
hawkbit-01_1  | org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
hawkbit-01_1  | 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
hawkbit-01_1  | 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:223)
hawkbit-01_1  | 	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:156)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
hawkbit-01_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
hawkbit-01_1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
hawkbit-01_1  | 	at org.eclipse.hawkbit.repository.jpa.JpaDeploymentManagement$$EnhancerBySpringCGLIB$$ed422bba.countActionsByTarget(<generated>)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.data.providers.ActionDataProvider.sizeInBackEnd(ActionDataProvider.java:65)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.data.providers.ActionDataProvider.sizeInBackEnd(ActionDataProvider.java:29)
hawkbit-01_1  | 	at org.eclipse.hawkbit.ui.common.data.providers.AbstractGenericDataProvider.sizeInBackEnd(AbstractGenericDataProvider.java:70)
hawkbit-01_1  | 	at com.vaadin.data.provider.AbstractBackEndDataProvider.size(AbstractBackEndDataProvider.java:66)
hawkbit-01_1  | 	at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85)
hawkbit-01_1  | 	at com.vaadin.data.provider.DataCommunicator.getDataProviderSize(DataCommunicator.java:815)
hawkbit-01_1  | 	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:359)
hawkbit-01_1  | 	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:339)
hawkbit-01_1  | 	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
hawkbit-01_1  | 	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:168)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:150)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:247)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:550)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
hawkbit-01_1  | 	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
hawkbit-01_1  | 	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
hawkbit-01_1  | 	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
hawkbit-01_1  | 	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
hawkbit-01_1  | 	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345)
hawkbit-01_1  | 	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340)
hawkbit-01_1  | 	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:448)
hawkbit-01_1  | 	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272)
hawkbit-01_1  | 	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.jsr356.messages.TextWholeMessage.messageComplete(TextWholeMessage.java:59)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrEndpointEventDriver.onTextFrame(JsrEndpointEventDriver.java:228)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:152)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:326)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:148)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:113)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:168)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:92)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:202)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:225)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:259)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:459)
hawkbit-01_1  | 	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:440)
hawkbit-01_1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
hawkbit-01_1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
hawkbit-01_1  | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
hawkbit-01_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
hawkbit-01_1  | 	at java.lang.Thread.run(Thread.java:748)
```

Following errors (copied only the error messages, the rest is repeating):

```
hawkbit-01_1  | 2021-08-27 15:38:40.107 ERROR 1 --- [tp1151512955-22] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI: 
hawkbit-01_1  | 
hawkbit-01_1  | org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
hawkbit-01_1  | 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
hawkbit-01_1  | 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:223)

hawkbit-01_1  | 2021-08-27 15:38:49.772 ERROR 1 --- [tp1151512955-22] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI: 
hawkbit-01_1  | 
hawkbit-01_1  | java.lang.IllegalArgumentException: Cannot find cache named 'tenantConfiguration' for Builder[public org.eclipse.hawkbit.repository.model.TenantConfigurationValue org.eclipse.hawkbit.repository.jpa.JpaTenantConfigurationManagement.getConfigurationValue(java.lang.String,java.lang.Class)] caches=[tenantConfiguration] | key='#configurationKeyName' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'
hawkbit-01_1  | 	at org.springframework.cache.interceptor.AbstractCacheResolver.resolveCaches(AbstractCacheResolver.java:92)

hawkbit-01_1  | 
hawkbit-01_1  | 2021-08-27 15:39:02.365 ERROR 1 --- [tp1151512955-22] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI: 
hawkbit-01_1  | 
hawkbit-01_1  | java.lang.IllegalArgumentException: Cannot find cache named 'tenantConfiguration' for Builder[public org.eclipse.hawkbit.repository.model.TenantConfigurationValue org.eclipse.hawkbit.repository.jpa.JpaTenantConfigurationManagement.getConfigurationValue(java.lang.String,java.lang.Class)] caches=[tenantConfiguration] | key='#configurationKeyName' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'
hawkbit-01_1  | 	at org.springframework.cache.interceptor.AbstractCacheResolver.resolveCaches(AbstractCacheResolver.java:92)
hawkbit-01_1  | 	at org.springframework.cache.interceptor.CacheAspectSupport.getCaches(CacheAspectSupport.java:253)

hawkbit-01_1  | 2021-08-27 15:39:15.807 ERROR 1 --- [tp1151512955-22] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI: 
hawkbit-01_1  | 
hawkbit-01_1  | java.lang.IllegalArgumentException: Cannot find cache named 'tenantConfiguration' for Builder[public org.eclipse.hawkbit.repository.model.TenantConfigurationValue org.eclipse.hawkbit.repository.jpa.JpaTenantConfigurationManagement.getConfigurationValue(java.lang.String,java.lang.Class)] caches=[tenantConfiguration] | key='#configurationKeyName' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'
hawkbit-01_1  | 	at org.springframework.cache.interceptor.AbstractCacheResolver.resolveCaches(AbstractCacheResolver.java:92)
hawkbit-01_1  | 	at org.springframework.cache.interceptor.CacheAspectSupport.getCaches(CacheAspectSupport.java:253)
```

I am able to login into MySQL container using database, username and password specified in Hawkbit container config and verified the data can be accessed (ran few SQL queries in MySQL shell under Hawkbit user).

Let me know what other data/information can help.

**Comment by bogdan-bondar** [comment]
Hi @mdymov-hayward ! It seems you either use the custom theme or override the `MyUI` class yourself. In either case make sure you annotate your Vaadin UI class with `@Push(value = PushMode.AUTOMATIC, transport = Transport.WEBSOCKET_XHR)` (see https://github.com/eclipse/hawkbit-examples/commit/8e6323b5426dafbb7cdf27f39af070ecee8ae693). I will make sure you will not loose the Security Context during Vaadin client/server RPC calls.

**Comment by mdymov-hayward** [comment]
Hi @bogdan-bondar,

thank you for quick response. We do use the example MyUI.java virtually unchanged, the only differences I see are couple of customization lines for Vaadin with @Title and @Theme, and we use Transport.WEBSOCKET instead of Transport.WEBSOCKET_XHR.

Here is the code:

`
/**
 * Example hawkBit UI implementation.
 * 
 * A {@link SpringUI} annotated class must be present in the classpath. The
 * easiest way to get an hawkBit UI running is to extend the
 * {@link AbstractHawkbitUI} and to annotated it with {@link SpringUI} as in
 * this example.
 *
 */
@SpringUI
@Push(value = PushMode.AUTOMATIC, transport = Transport.WEBSOCKET)
@Title("Hayward Hawkbit")
@Theme(value = "hayward")
@SuppressWarnings({ "squid:MaximumInheritanceDepth" })
public class MyUI extends AbstractHawkbitUI {

    private static final long serialVersionUID = 1L;

    @Autowired
    MyUI(final EventPushStrategy pushStrategy, final UIEventBus eventBus, final UIEventProvider eventProvider,
            final SpringViewProvider viewProvider, final ApplicationContext context, final DashboardMenu dashboardMenu, 
            final ErrorView errorview, final NotificationUnreadButton notificationUnreadButton, 
            final UiProperties uiProperties, final VaadinMessageSource i18n) {
        super(pushStrategy, eventBus, eventProvider, viewProvider, context, dashboardMenu, errorview, 
                notificationUnreadButton, uiProperties, i18n);
    }
}
`

I can rebuild the image with Transport.WEBSOCKET_XHR just to make it match the example but not confident this will make any difference. 

Is there anything else you can see as problematic in the source?

**Comment by bogdan-bondar** [comment]
`Transport.WEBSOCKET_XHR` is essential here. I won't go into the details of Vaadin/Spring security but it should resolve your issue. Please confirm

**Comment by mdymov-hayward** [comment]
That was it - changing from Transport.WEBSOCKET to Transport.WEBSOCKET_XHR resolved the issue! I can now access all devices/distribution sets/rollouts as usual. This is running in local docker container, next step will be to push the change to Google Cloud Run and see if this works in GCP K8 cluster too. Thank you @bogdan-bondar !
