### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by lreinecke** [eclipse/hawkbit#1231]
I have tried to build the M7 Tag multiple times. Every time it crashes.
I use following Software:

- Windows 10
- MariaDB 10.7.3
- RabbitMQ 3.8.27
- AdoptOpenJDK 11.0.14.1
- hawkBit 0.3.0M7
- Maven 3.8.4

It crashes on the following steps:

- `hawkBit :: Repository :: JPA Implementation`: The Error ist in the Log-File from the test set: `org.eclipse.hawkbit.repository.jpa.autocleanup.AutoActionCleanupTest`
- `hawkBit :: REST :: Management Resources`: The Error ist in the Log-File from the test set: `org.eclipse.hawkbit.mgmt.rest.resource.MgmtDistributionSetTypeResourceTest`

I configured everything like [here](https://www.eclipse.org/hawkbit/guides/runhawkbit/).
MariaDB and rabbitMQ are running the whole time and the Usercredentials are ok.
Every time it prompts `Flyway upgrade recommended: H2 1.4.200 is newer than this version of Flyway and support has not been tested.` But this is probably not the cause of the error.
I captured some data: [Captured Data.zip](https://github.com/eclipse/hawkbit/files/8097498/Captured.Data.zip)
 
In two tries of about 30 with an older MariaDB version it ran to `hawkBit :: Runtime :: Update Server`. Then the message was `Unsupported Database: MariaDB 10.2`. But on your website in the Tutorial you explain how to use MariaDB. Which Version of this DB should I use?

Im stuck at this and hope you can help me.

**Comment by lreinecke** [comment]
When I add the Flag -DskipTests the build-process completes. I can log in to this Server successfully. But I suppose the test are needed for a productive System.

**Comment by lreinecke** [comment]
And when I try to run it with the MariaDB it throws following error:
```
2022-02-21 16:08:31.580  WARN 1424 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.eclipse.hawkbit.repository.jpa.RepositoryApplicationConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver
2022-02-21 16:08:31.626  INFO 1424 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-02-21 16:08:31.642 ERROR 1424 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.eclipse.hawkbit.repository.jpa.RepositoryApplicationConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:799)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1203)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:229)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.eclipse.hawkbit.app.Start.main(Start.java:35)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:886)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:790)
        ... 37 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652)
        ... 51 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver
        at org.springframework.util.Assert.state(Assert.java:97)
        at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:224)
        at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:176)
        at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:43)
        at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari.dataSource(DataSourceConfiguration.java:85)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 52 common frames omitted
```

**Comment by floruschbaschan** [comment]
Hey @lreinecke,
thanks for opening the issue. It looks like the required mariadb dependency is missing. Please have a look at my [comment here](https://github.com/eclipse/hawkbit/issues/963#issuecomment-864771711) and let me know if this fixes your issue.

**Comment by lreinecke** [comment]
Hey,
this resolved the problems for the mariadb driver. I had accidentally two dependencies in my pom.xml. One with `test` and one with `compile`. Deleting the one with `test` was the solution.
But the problems with the unittests remains the same.
When I try to run the Server it crashes because MariaDB 10.7 is not supported. Do you know which version is needed? I don't find any documentation which one to use.

Are the test, that I skip with the `-DskipTests` Flag needed for a productive deployment? I get the same error with the 0.3.0M7 and the newest master branch. Both produce the errors in my first comment.

**Comment by lreinecke** [comment]
I was wrong. The build seems to work now. But ist throws an error, that MariaDB 10.7 is not supported. Which one can I use?

**Comment by lreinecke** [comment]
The errors at the unittests are still the same.

**Comment by floruschbaschan** [comment]
I tried to reproduce your problem with MariaDB 10.2, 10.4 and 10.7 on Linux (Ubuntu 20.04) as well as Windows 10. But I was not able to run into any similar error here. Everything was working as expected. 

How do you start the application? Have you checked out the latest master branch of hawkBit?

Regarding your question about skipping test for a productive deployment. Yes, IMHO it makes a lot of sense that every test passes before you are going to deploy any application into a productive environment.

As a sidenode, while looking at your error logs, I noticed that you don't use any of hawkBits default profiles. There is an own profile for each database that is supported. Please have a look [here](https://github.com/eclipse/hawkbit/tree/master/hawkbit-runtime/hawkbit-update-server/src/main/resources).

**Comment by lreinecke** [comment]
I am very sure I found the cause of the failures. The Machine I tried to build it on had only a total of 4GB RAM of those only 2GB where free. So you couldn't reproduce it because your machine has probably more RAM. I tried it on a machine with more RAM and it didn't throw these errors. But it got stuck on the Database. I used the tag 0.3.0M7. The error message stated that MariaDB 10.7 is not supported.

Here is my output of the build process:
[output.txt](https://github.com/eclipse/hawkbit/files/8124418/output.txt)

**Comment by floruschbaschan** [comment]
In my case `mvn clean install --debug -Dspring.profiles.active=mysql` was successful. But I can see the following warnings: `Flyway upgrade recommended: MariaDB 10.7 is newer than this version of Flyway and support has not been tested. The latest supported version of MariaDB is 10.4`. Have you tried MariaDB 10.4 instead as suggested by Flyway?

**Comment by lreinecke** [comment]
When I try to run it even with `-Dspring.profiles.active=mysql` the message I recieve is: `Flyway upgrade recommended: H2 1.4.200 is newer than this version of Flyway and support has not been tested.`. Do you know why it says `H2`?

My `pom.xml` file looks like this:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>org.eclipse.hawkbit</groupId>
      <artifactId>hawkbit-runtime-parent</artifactId>
      <version>0.3.0-SNAPSHOT</version>
   </parent>
   <artifactId>hawkbit-update-server</artifactId>
   <name>hawkBit :: Runtime :: Update Server</name>

   <build>
      <plugins>
         <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <executions>
               <execution>
                  <goals>
                     <goal>repackage</goal>
                  </goals>
                  <configuration>
                     <outputDirectory>${baseDir}</outputDirectory>
                     <mainClass>org.eclipse.hawkbit.app.Start</mainClass>
                     <layout>JAR</layout>
                  </configuration>
               </execution>
            </executions>
         </plugin>
      </plugins>
      <resources>
         <resource>
            <directory>src/main/resources</directory>
         </resource>
      </resources>
   </build>

   <dependencies>
      <dependency>
         <groupId>org.eclipse.hawkbit</groupId>
         <artifactId>hawkbit-boot-starter</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>com.h2database</groupId>
         <artifactId>h2</artifactId>
      </dependency>
      <dependency>
         <groupId>com.microsoft.sqlserver</groupId>
         <artifactId>mssql-jdbc</artifactId>
      </dependency>
      <dependency>
         <groupId>org.postgresql</groupId>
         <artifactId>postgresql</artifactId>
      </dependency>

      <dependency>
         <groupId>org.mariadb.jdbc</groupId>
         <artifactId>mariadb-java-client</artifactId>
         <scope>compile</scope>
      </dependency>

      <!-- Test -->
      <dependency>
         <groupId>io.qameta.allure</groupId>
         <artifactId>allure-junit5</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-test</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>org.springframework.security</groupId>
         <artifactId>spring-security-test</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>org.eclipse.hawkbit</groupId>
         <artifactId>hawkbit-repository-test</artifactId>
         <version>${project.version}</version>
         <scope>test</scope>
      </dependency>
   </dependencies>

</project>
```

`application.properties`:
```
# User Security
spring.security.user.name=admin
spring.security.user.password={noop}admin
spring.main.allow-bean-definition-overriding=true

# Http Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# DDI authentication configuration
hawkbit.server.ddi.security.authentication.anonymous.enabled=false
hawkbit.server.ddi.security.authentication.targettoken.enabled=false
hawkbit.server.ddi.security.authentication.gatewaytoken.enabled=false

# Optional events
hawkbit.server.repository.publish-target-poll-event=false

## Configuration for DMF/RabbitMQ integration
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Define own users instead of default "admin" user:
#hawkbit.server.im.users[0].username=hawkbit
#hawkbit.server.im.users[0].password={noop}isAwesome!
#hawkbit.server.im.users[0].firstname=Eclipse
#hawkbit.server.im.users[0].lastname=HawkBit
#hawkbit.server.im.users[0].permissions=ALL

# Enable CORS and specify the allowed origins:
#hawkbit.server.security.cors.enabled=true
#hawkbit.server.security.cors.allowedOrigins=http://localhost

spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/hawkbit
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

spring.profiles.active=mysql
```

`application-mysql.properties`:
```
spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/hawkbit
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
```

All the passwords are correct. I know that I have to use stronger passwords in the finished deployment.

I don't know how to tell the compiler to use MariaDB instead of H2.

**Comment by lreinecke** [comment]
The message with the outdated H2 doesn't show anymore. But I tried multiple versions of MariaDB. All of them didn't work. I tried Versions 10.7, 10.4, 10.3 and 10.2. Every time the same error. The Flyway version in use should work with 10.3 or 10.2 according to their patch notes. But the error stays the same.
The output looked like this: [output.txt](https://github.com/eclipse/hawkbit/files/8215784/output.txt)

**Comment by lreinecke** [comment]
The README says this:
![grafik](https://user-images.githubusercontent.com/96118883/157626782-4bc1fdcc-0d74-4e6e-85da-f7af182b5991.png)
But MariaDB says ist is only version 5.5.5:
![grafik](https://user-images.githubusercontent.com/96118883/157626957-823082bf-81c3-4bb9-a0fc-0ba23fad0d72.png)
Could this cause any problems?

**Comment by lreinecke** [comment]
Do I have to configure the Versions of the DB Connectors etc. in any `pom.xml`?

**Comment by workpush** [comment]
I have the same issue trying to run hawkbit with mariadb:10.5!
```
﻿﻿Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.5
```

**Comment by lreinecke** [comment]
I added `useMysqlMetadata=true` to the URL from the DB. The DB properties noe are looking like this:
```
spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/hawkbit?useMysqlMetadata=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
```
Now my output looks like this: [output.txt](https://github.com/eclipse/hawkbit/files/8303240/output.txt)
There where also tables in the DB after the build failed again, so I think this solved my problem with the MariaDB.

But it still throws those errors:
```
[ERROR] Errors: 
[ERROR]   AllowedHostNamesTest.allowedHostNameWithAllowedHost » IllegalState Failed to l...
[ERROR]   AllowedHostNamesTest.allowedHostNameWithNotAllowedHost » IllegalState Failed t...
[ERROR]   AllowedHostNamesTest.notAllowedHostnameWithIgnoredPath » IllegalState Failed t...
[ERROR]   CorsTest.validateCorsRequest » IllegalState Failed to load ApplicationContext
```
Do you know how to solve them?

**Comment by lreinecke** [comment]
The build process now writes data to the DB. But it never completes the DB migration.
The Table `schema_version` looks like this:
![grafik](https://user-images.githubusercontent.com/96118883/159010872-cbad2a87-668d-4add-b70b-aeceb0c55cf7.png)
But the step, on which it stops is different every time. The errors from my last comment are also still there.

**Comment by lreinecke** [comment]
I manually reran the SQL Scripts and then set the value of `success` to `1`. Then a rerun of the build was successfull. But the Data, that I saved in the GUI was written to a temporary H2 DB, not to my MariaDB. But I need a sysem where the Data is persisted.

The Uotputs where:
Build: [output.txt](https://github.com/eclipse/hawkbit/files/8332312/output.txt)
Run: [output_running.txt](https://github.com/eclipse/hawkbit/files/8332321/output_running.txt)

**Comment by lreinecke** [comment]
When I try to use MySQL it says, that it can cause error with the MariaDB Driver. I tried to switch to a Driver for MySQL but it cant find any POM for it.
[output.txt](https://github.com/eclipse/hawkbit/files/8333321/output.txt)
hawkbit-runtime/hawkbit-update-server/pom.xml: [pom.xml.txt](https://github.com/eclipse/hawkbit/files/8333336/pom.xml.txt)

**Comment by workpush** [comment]
@lreinecke Could you solve it? How?

**Comment by lreinecke** [comment]
@workpush 

> @lreinecke Could you solve it? How?


I switched to MySQL. Then it worked fine. You need to modify following files:
### \hawkbit-runtime\hawkbit-update-server\pom.xml
You need to add this Dependency:
```
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.28</version>
</dependency>
```
This Version of the Connector worked for me. Also you dont't have to change the `test` to `compile` for the MariaDB.
### \hawkbit-runtime\hawkbit-update-server\src\main\resources\application-mysql.properties
This should look something like this:
```
spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://<path to MySQL>:3306/hawkbit
spring.datasource.username=XXXXXX
spring.datasource.password=XXXXXX
```
The last line with the `driverClassName` could be removed. The system could find the apropriate driver for its own.

If you need to run MariaDB and can't switch to MySQL I could not help you.

So my Problem with MariaDB wasn't solved but I can work with hawkBit now. And this Issue can stay closed.
