### ISSUE TITLE
ERROR 2996

### ISSUE THREAD

**Issue by lreinecke** [eclipse/hawkbit#1312]
When I try to run the Server it throws the Error 2996 with the message:
```
2023-01-19 11:30:42.373 ERROR 2996 --- [sphere-Shared-6] c.v.s.c.PushAtmosphereHandler            : Exception in push connection

java.io.IOException: Socket closed {}
        at org.atmosphere.container.version.JSR356WebSocket.write(JSR356WebSocket.java:66)
        at org.atmosphere.websocket.WebSocket.write(WebSocket.java:255)
        at org.atmosphere.websocket.WebSocket.write(WebSocket.java:220)
        at org.atmosphere.websocket.WebSocket.write(WebSocket.java:46)
        at org.atmosphere.cpr.AtmosphereResponseImpl$Stream.write(AtmosphereResponseImpl.java:957)
        at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:155)
        at com.vaadin.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:52)
        at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1037)
        at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1057)
        at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:871)
        at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2023-01-19 11:30:42.375 ERROR 2996 --- [sphere-Shared-6] c.v.server.communication.PushHandler     : Could not get resource. This should never happen.
```
The Server runs without other problems that I have seen so far.
It shows, when I log in to multiple users the same time. When I log the last of them out the error gets thrown.

**Comment by lreinecke** [comment]
I run the newest commit.
Commit number: b919ceda5c71116c65c9b537e4f7aa23d99fb111

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/
