### ISSUE TITLE
hawkBit UI issue after 0.3.0M8 version upgrade

### ISSUE THREAD

**Issue by MB-Kiwigrid** [eclipse/hawkbit#1354]
Hello team, I tried to update the new hawkBit release version from 0.3.0M7 to 0.3.0M8 and run into below runtime issue  when i tried to login to hawkBit user interface locally .

Error message : 

`java.lang.ClassCastException: class org.springframework.security.oauth2.core.user.DefaultOAuth2User cannot be cast to class org.springframework.security.oauth2.core.oidc.user.OidcUser (org.springframework.security.oauth2.core.user.DefaultOAuth2User and org.springframework.security.oauth2.core.oidc.user.OidcUser are in unnamed module of loader 'app')
	at org.eclipse.hawkbit.ui.common.UserDetailsFormatter.getCurrentUser(UserDetailsFormatter.java:184) ~[hawkbit-ui-0.3.0M8.jar:0.3.0M8]
	at org.eclipse.hawkbit.ui.common.UserDetailsFormatter.formatCurrentTenant(UserDetailsFormatter.java:137) ~[hawkbit-ui-0.3.0M8.jar:0.3.0M8]
	at org.eclipse.hawkbit.ui.menu.DashboardMenu.buildUserMenu(DashboardMenu.java:204) ~[hawkbit-ui-0.3.0M8.jar:0.3.0M8]
	at org.eclipse.hawkbit.ui.menu.DashboardMenu.buildContent(DashboardMenu.java:113) ~[hawkbit-ui-0.3.0M8.jar:0.3.0M8]
	at org.eclipse.hawkbit.ui.menu.DashboardMenu.init(DashboardMenu.java:103) ~[hawkbit-ui-0.3.0M8.jar:0.3.0M8]
	at org.eclipse.hawkbit.ui.AbstractHawkbitUI.init(AbstractHawkbitUI.java:143) ~[hawkbit-ui-0.3.0M8.jar:0.3.0M8]
	at com.vaadin.ui.UI.doInit(UI.java:771) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:218) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:76) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637) ~[vaadin-server-8.14.3.jar:8.14.3]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464) ~[vaadin-server-8.14.3.jar:8.14.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.
....
....
.....
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]`

Configured Keycloak 19 to integrate OpenId to Hawkbit.

Let me know if you need any other information

**Comment by strailov** [comment]
Hello @MB-Kiwigrid  ! 

I think this might be related to https://github.com/eclipse/hawkbit/pull/1204 which soon will be merged. 
Maybe you could give it a try ?

**Comment by MB-Kiwigrid** [comment]
Hello @strailov , Thanks for your reply. We tried this pull request [1122](https://github.com/eclipse/hawkbit/pull/1122) which resolved the problem. 

Definitely i will give a try with above suggested pull request to see the result and update you.

**Comment by MB-Kiwigrid** [comment]
@strailov I tried the above solution with the minimal customised code, but unfortunately it did not work as we expected. As there are lot of internal calls to different methods need to be customised . Maybe I need to wait until this pull request is merged.

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/
