### ISSUE TITLE
hawkBit demo server not accessible and failed tests on module build of Repository JPA Implementation

### ISSUE THREAD

**Issue by jkaa** [eclipse/hawkbit#290]
The server under https://hawkbit.eu-gb.mybluemix.net/UI/ responds with different errors like:
- JPA exception or
- `"Failed to load the bootstrap javascript: ./../VAADIN/vaadinBootstrap.js?v=7.6.5");
  vaadin.initApplication("UI-2708",{"theme":"hawkbit","versionInfo":{"vaadinVersion":"7.6.5","atmosphereVersion":"2.2.7.vaadin1"},"widgetset":"org.eclipse.hawkbit.ui.AppWidgetSet","comErrMsg":{"caption":"Communication problem","message":"Take note of any unsaved data, and <u>click here</u> or press ESC to continue.","url":null},"authErrMsg":{"caption":"Authentication problem","message":"Take note of any unsaved data, and <u>click here</u> or press ESC to continue.","url":null},"sessExpMsg":{"caption":"Session Expired","message":"Take note of any unsaved data, and <u>click here</u> or press ESC key to continue.","url":null},"vaadinDir":"./../VAADIN/","standalone":true,"heartbeatInterval":60,"serviceUrl":"."}`

Furthermore 
- credentials `admin:admin` seems not to work

**Local build with skipped tests results in inaccessible/error reporting hawkBit server**

**The local build fails at JPA test:**

`storesWrongFormattedStringAsPollingInterval(org.eclipse.hawkbit.repository.jpa.T
enantConfigurationManagementTest)  Time elapsed: 1.089 sec  <<< ERROR!
com.mongodb.MongoTimeoutException: Timed out after 500 ms while waiting for a se
rver that matches ReadPreferenceServerSelector{readPreference=primary}. Client v
iew of cluster state is {type=UNKNOWN, servers=[{address=localhost:51531, type=U
NKNOWN, state=CONNECTING}]
        at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster
.java:369)
        at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)

```
    at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<in
```

it>(ClusterBinding.java:75)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<in
it>(ClusterBinding.java:71)
        at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBin
ding.java:63)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.
java:210)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:482)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:79)
        at com.mongodb.Mongo.execute(Mongo.java:772)
        at com.mongodb.Mongo$2.execute(Mongo.java:759)
        at com.mongodb.DBCursor.initializeCursor(DBCursor.java:851)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:152)
        at com.mongodb.gridfs.GridFS.find(GridFS.java:247)
        at com.mongodb.gridfs.GridFS.find(GridFS.java:227)
        at com.mongodb.gridfs.GridFS.remove(GridFS.java:310)
        at org.springframework.data.mongodb.gridfs.GridFsTemplate.delete(GridFsT
emplate.java:207)
        at org.eclipse.hawkbit.repository.test.util.AbstractIntegrationTest.clea
nCurrentCollection(AbstractIntegrationTest.java:205)
        at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.ja
va:33)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethod
Callbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.junit.rules.TestWatchman$1.evaluate(TestWatchman.java:53)
        at org.eclipse.hawkbit.repository.test.util.WithSpringAuthorityRule$1.ev
aluate(WithSpringAuthorityRule.java:40)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evalu
ate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runCh
ild(SpringJUnit4ClassRunner.java:254)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runCh
ild(SpringJUnit4ClassRunner.java:89)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.
java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClass
Callbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.ja
va:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassC
allbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:193)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103)

Results :

Tests in error:
  RepositoryEntityEventTest>AbstractIntegrationTest.cleanCurrentCollection:205 »
 MongoTimeout
  EntityInterceptorListenerTest>AbstractIntegrationTest.cleanCurrentCollection:2
05 » MongoTimeout
  ModelEqualsHashcodeTest>AbstractIntegrationTest.cleanCurrentCollection:205 » M
ongoTimeout
  ReportManagementTest>AbstractIntegrationTest.cleanCurrentCollection:205 » Mong
oTimeout
  RolloutManagementTest>AbstractIntegrationTest.cleanCurrentCollection:205 » Mon
goTimeout
  RSQLActionFieldsTest>AbstractIntegrationTest.cleanCurrentCollection:205 » Mong
oTimeout
  RSQLSoftwareModuleFieldTest>AbstractIntegrationTest.cleanCurrentCollection:205
 » MongoTimeout
  RSQLSoftwareModuleTypeFieldsTest>AbstractIntegrationTest.cleanCurrentCollectio
n:205 » MongoTimeout
  SoftwareManagementTest>AbstractIntegrationTest.cleanCurrentCollection:205 » Mo
ngoTimeout
  TagManagementTest>AbstractIntegrationTest.cleanCurrentCollection:205 » MongoTi
meout
  TargetManagementSearchTest>AbstractIntegrationTest.cleanCurrentCollection:205
» MongoTimeout
  TargetManagementTest>AbstractIntegrationTest.cleanCurrentCollection:205 » Mong
oTimeout
  MultiTenancyEntityTest>AbstractIntegrationTest.cleanCurrentCollection:205 » Mo
ngoTimeout
  TenantConfigurationManagementTest>AbstractIntegrationTest.cleanCurrentCollecti
on:205 » MongoTimeout`

**Comment by michahirsch** [comment]
Hi @jkaa,

* The hawkBit sandbox app had some trouble, and is working again. You can now login again to the sandbox app.

* To your build problems, it seems like all test-cases with MongoDB are failing. hawkBit is using https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo to download a MongoDB once the test are started. Spring offers an out-of-the-shelf embedded MongoDB flapdoodle integration http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html. You should see something like this on your console when the MongoDB gets downloaded
```
2016-09-14 09:04:03.893  INFO 14996 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.ChannelBindingServiceConfiguration$PostProcessorConfiguration' of type [class org.springframework.cloud.stream.config.ChannelBindingServiceConfiguration$PostProcessorConfiguration$$EnhancerBySpringCGLIB$$a8c53fb] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-09-14 09:04:04.139  INFO 14996 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.7:Windows:B64 : starting...
2016-09-14 09:04:04.738  INFO 14996 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.7:Windows:B64 : DownloadSize: 149357757
2016-09-14 09:04:04.739  INFO 14996 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.7:Windows:B64 : 0 %
2016-09-14 09:04:21.914  INFO 14996 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.7:Windows:B64 : 10 %
2016-09-14 09:04:50.090  INFO 14996 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.7:Windows:B64 : 20 %
```
Are you sitting behind a proxy? If yes then you need to add java proxy settings to the build
```
mvn clean install -Dhttp.proxyHost=myProxy -Dhttp.proxyPort=3128 -Dhttps.proxyHost=myProxy -Dhttps.proxyPort=3128
```

Hope this helps.
Cheers,
Michael

**Comment by jkaa** [comment]
Hello Michael,

I really appreciate your quick response.

- Sandbox is working again, thanks
- build problem still present

- I tried with direct internet acccess (no proxy)
  - Unfortunately I do not see any download messages of the embedded mongo db
  - I can provide you with a log of the build, If needed

mongoDB errors:
--
`2016-09-14 16:20:19.982  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:19.982+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:59359 #2 (2 connections now open)
2016-09-14 16:20:19.984  INFO 29200 --- [           main] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:2}] to localhost:59328
2016-09-14 16:20:20.029  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.029+0200 I INDEX    [conn2] build index on: spArtifactRepositoryc8109af096627c6b08c6bff78fe55f90.fs.files properties: { v: 1, key: { filename: 1, uploadDate: 1 }, name: "filename_1_uploadDate_1", ns: "spArtifactRepositoryc8109af096627c6b08c6bff78fe55f90.fs.files" }
2016-09-14 16:20:20.030  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.029+0200 I INDEX    [conn2] 	 building index using bulk method
2016-09-14 16:20:20.030  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.030+0200 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs
2016-09-14 16:20:20.050  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.050+0200 I INDEX    [conn2] build index on: spArtifactRepositoryc8109af096627c6b08c6bff78fe55f90.fs.chunks properties: { v: 1, unique: true, key: { files_id: 1, n: 1 }, name: "files_id_1_n_1", ns: "spArtifactRepositoryc8109af096627c6b08c6bff78fe55f90.fs.chunks" }
2016-09-14 16:20:20.050  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.050+0200 I INDEX    [conn2] 	 building index using bulk method
2016-09-14 16:20:20.051  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.051+0200 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs
2016-09-14 16:20:20.140  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.140+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:59360 #3 (3 connections now open)
2016-09-14 16:20:20.141  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.140+0200 I COMMAND  [conn3] terminating, shutdown command received
2016-09-14 16:20:20.141  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.140+0200 I FTDC     [conn3] Shutting down full-time diagnostic data capture
2016-09-14 16:20:20.142  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.142+0200 I CONTROL  [conn3] now exiting
2016-09-14 16:20:20.142  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.142+0200 I NETWORK  [conn3] shutdown: going to close listening sockets...
2016-09-14 16:20:20.142  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.142+0200 I NETWORK  [conn3] closing listening socket: 428
2016-09-14 16:20:20.143  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.142+0200 I NETWORK  [conn3] shutdown: going to flush diaglog...
2016-09-14 16:20:20.143  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.142+0200 I NETWORK  [conn3] shutdown: going to close sockets...
2016-09-14 16:20:20.143  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.143+0200 I STORAGE  [conn3] WiredTigerKVEngine shutting down
2016-09-14 16:20:20.144  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.143+0200 I NETWORK  [conn2] end connection 127.0.0.1:59359 (2 connections now open)
2016-09-14 16:20:20.144  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.143+0200 I NETWORK  [conn1] end connection 127.0.0.1:59334 (2 connections now open)
2016-09-14 16:20:20.156  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.156+0200 I STORAGE  [conn3] shutdown: removing fs lock...
2016-09-14 16:20:20.157  INFO 29200 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-09-14T16:20:20.156+0200 I CONTROL  [conn3] dbexit:  rc: 0
2016-09-14 16:20:20.292  WARN 29200 --- [           main] org.mongodb.driver.connection            : Got socket exception on connection [connectionId{localValue:2, serverValue:2}] to localhost:59328. All connections to localhost:59328 will be closed.
2016-09-14 16:20:20.293  INFO 29200 --- [           main] org.mongodb.driver.connection            : Closed connection [connectionId{localValue:2, serverValue:2}] to localhost:59328 because there was a socket exception raised by this connection.
2016-09-14 16:20:20.296  INFO 29200 --- [           main] org.mongodb.driver.cluster               : No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=STANDALONE, connectionMode=MULTIPLE, all=[ServerDescription{address=localhost:59328, type=UNKNOWN, state=CONNECTING}]}. Waiting for 500 ms before timing out
2016-09-14 16:20:20.810  INFO 29200 --- [           main] org.mongodb.driver.cluster               : No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=STANDALONE, connectionMode=MULTIPLE, all=[ServerDescription{address=localhost:59328, type=UNKNOWN, state=CONNECTING}]}. Waiting for 500 ms before timing out
2016-09-14 16:20:21.298  INFO 29200 --- [localhost:59328] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:59328

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	... 3 common frames omitted

2016-09-14 16:20:21.311  INFO 29200 --- [           main] org.mongodb.driver.cluster               : No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=STANDALONE, connectionMode=MULTIPLE, all=[ServerDescription{address=localhost:59328, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]}. Waiting for 500 ms before timing out
2016-09-14 16:20:21.892  INFO 29200 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Closing org.springframework.web.context.support.GenericWebApplicationContext@110318a7: startup date [Wed Sep 14 16:20:06 CEST 2016]; root of context hierarchy
2016-09-14 16:20:21.914  INFO 29200 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.736 sec - in org.eclipse.hawkbit.repository.jpa.ArtifactManagementFailedMongoDBTest
Running org.eclipse.hawkbit.repository.jpa.ArtifactManagementTest
2016-09-14 16:20:21.927  INFO 29200 --- [           main] o.s.t.c.support.AbstractContextLoader    : Could not detect default resource locations for test class [org.eclipse.hawkbit.repository.jpa.AbstractJpaIntegrationTestWithMongoDB]: no resource found for suffixes {-context.xml, Context.groovy}.
2016-09-14 16:20:21.928  INFO 29200 --- [           main] o.s.t.c.support.AbstractContextLoader    : Could not detect default resource locations for test class [org.eclipse.hawkbit.repository.test.util.AbstractIntegrationTest]: no resource found for suffixes {-context.xml, Context.groovy}.
2016-09-14 16:20:21.930  INFO 29200 --- [           main] o.s.t.c.web.WebTestContextBootstrapper   : Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener]
2016-09-14 16:20:21.931  INFO 29200 --- [           main] o.s.t.c.web.WebTestContextBootstrapper   : Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@252a59fc, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@1d714998, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@7fb920d3, org.springframework.test.context.support.DirtiesContextTestExecutionListener@546a8d41, org.springframework.test.context.transaction.TransactionalTestExecutionListener@2378db89, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@34d27bf7]
`

**Comment by michahirsch** [comment]
Hi,

that is very weird. Seems like the mongoDB is running and seems to work due the logging
```
2016-09-14 16:20:19.982 INFO 29200 --- [ Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo : 2016-09-14T16:20:19.982+0200 I NETWORK [initandlisten] connection accepted from 127.0.0.1:59359 #2 (2 connections now open)
2016-09-14 16:20:19.984 INFO 29200 --- [ main] org.mongodb.driver.connection : Opened connection [connectionId{localValue:2, serverValue:2}] to localhost:59328
2016-09-14 16:20:20.029 INFO 29200 --- [ Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo : 2016-09-14T16:20:20.029+0200 I INDEX [conn2] build index on: spArtifactRepositoryc8109af096627c6b08c6bff78fe55f90.fs.files properties: { v: 1, key: { filename: 1, uploadDate: 1 }, name: "filename_1_uploadDate_1", ns: "spArtifactRepositoryc8109af096627c6b08c6bff78fe55f90.fs.files" }
```
But then a socket exception happening, that's very weird. 
```
2016-09-14 16:20:20.292 WARN 29200 --- [ main] org.mongodb.driver.connection : Got socket exception on connection [connectionId{localValue:2, serverValue:2}] to localhost:59328. All connections to localhost:59328 will be closed.
2016-09-14 16:20:20.293 INFO 29200 --- [ main] org.mongodb.driver.connection : Closed connection [connectionId{localValue:2, serverValue:2}] to localhost:59328 because there was a socket exception raised by this connection.
```

* Can you provide the full build log? 
* Have you tried running only the JUnit test? (not in a maven build)
* Which maven version you are using?

Cheers,
Michael

**Comment by jkaa** [comment]
Hi,

- build log attached
- Maven and JDK versions are:
  - 3.3.9
  - 1.8.0_60
- Haven't tried JUnit tests other than in maven (short on time)

Cheers,
Johannes

[hawkbit-buildlog.txt](https://github.com/eclipse/hawkbit/files/476118/hawkbit-buildlog.txt)

**Comment by michahirsch** [comment]
Hi,

thanks for the provided log-file. I cannot see any failure in the log why the tests cannot connect to the MongoDB.

There is a MongoDB downloaded and started as it looks like because there is the extracted `mongod` process.
```
C:\Users\USERX\AppData\Local\Temp\extract-b0275128-72e8-4ec3-96d1-e11fbba9a78aextractmongod.exe. Will try to delete it again when program exits.
```

Can you try deleting the local MongoDB again so flapdoodle will download it again? 
You should find the downloaded MongoDB here
Windows `C:\Users\USERX\.embedmongo` you can delete it then flapdoodle will download it again. 

Cheers,
Michael

**Comment by jkaa** [comment]
Hi Michael,

unfortunately tests are still failing with:
`com.mongodb.MongoTimeoutException: Timed out after 500 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:49828, type=UNKNOWN, state=CONNECTING}]`

I have ran into other socket timeout issues on my machine due to checkpoint security installed.
Is there a possibility to increase / provide the timeout by parameter?

Cheers,
Johannes

**Comment by michahirsch** [comment]
Hi Johannes,

it should be possible to configure the timeout according to the github issue https://github.com/spring-projects/spring-boot/issues/6062 you could just set the parameter `spring.mongodb.embedded.timeout=30000` to your build.

Like in maven `mvn clean install -Dspring.mongodb.embedded.timeout=30000` but I haven't tried it out yet.

Cheers,
Michael

**Comment by jkaa** [comment]
Hi Michael,

still the same exception: `...Timed out after 500 ms while waiting...`

Also tried: `-Dspring.data.mongodb.socketTimeout=10 -Dspring.data.mongodb.connectionTimeout=10`

Cheers

**Comment by faif** [comment]
The demo is not working for me either. Right now I see a JSON 500 Error. A few minutes ago I could access it but the admin:admin credentials were not working, both in the default login and after clicking the demo link.

**Comment by kaizimmerm** [comment]
The login issue with sandbox has been fixed.
