### ISSUE TITLE
Building master

### ISSUE THREAD

**Issue by sbabic** [eclipse/hawkbit#507]
Hi,

I tried today to build current master (I have already tried last week) and I get build errors. Building 0.2.0M3 works flawlessly, so I guess it is not strictly related to my build. I build in both cases with MariaDB enabled, that means I just patch pom.xml as:

diff --git a/hawkbit-runtime/hawkbit-update-server/pom.xml b/hawkbit-runtime/hawkbit-update-server/pom.xml
index 1d6d087..3788538 100644
--- a/hawkbit-runtime/hawkbit-update-server/pom.xml
+++ b/hawkbit-runtime/hawkbit-update-server/pom.xml
@@ -67,6 +67,20 @@
          <artifactId>h2</artifactId>
       </dependency>
 
+   
+      <dependency>
+         <groupId>org.mariadb.jdbc</groupId>
+         <artifactId>mariadb-java-client</artifactId>
+         <scope>compile</scope>
+      </dependency>
+ 
+      <dependency>
+         <groupId>org.eclipse.hawkbit</groupId>
+        <artifactId>hawkbit-extension-artifact-repository-mongo</artifactId>
+         <version>${project.version}</version>
+      </dependency>
+
+ 
    </dependencies>
 
 </project>

I see (one of many) errors like this (the last one):

2017-05-11 15:16:53,184  WARN main o.s.c.a.ConfigurationClassPostProcessor:373 - Cannot enhance @Configuration bean definition 'refreshScope' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2017-05-11 15:17:03,627 ERROR main o.e.h.r.t.u.AbstractIntegrationTest:220 - Test findRolloutGroupTargetsWithRsqlParam failed with {}.
org.junit.ComparisonFailure: expected:<"MyRollout--000[09]"> but was:<"MyRollout--000[11]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_121]
	at org.eclipse.hawkbit.repository.jpa.RolloutManagementTest.findRolloutGroupTargetsWithRsqlParam(RolloutManagementTest.java:1066) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75) ~[spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86) ~[spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.eclipse.hawkbit.repository.test.matcher.EventVerifier$1.evaluate(EventVerifier.java:56) ~[hawkbit-repository-test-0.2.0-SNAPSHOT.jar:0.2.0-SNAPSHOT]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) ~[junit-4.12.jar:4.12]
	at org.eclipse.hawkbit.repository.test.util.WithSpringAuthorityRule$1.evaluate(WithSpringAuthorityRule.java:41) ~[hawkbit-repository-test-0.2.0-SNAPSHOT.jar:0.2.0-SNAPSHOT]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) ~[junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252) [spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94) [spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191) [spring-test-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264) [surefire-junit4-2.17.jar:2.17]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.17.jar:2.17]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.17.jar:2.17]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200) [surefire-booter-2.17.jar:2.17]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.17.jar:2.17]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.17.jar:2.17]
Tests run: 38, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.393 sec <<< FAILURE! - in org.eclipse.hawkbit.repository.jpa.RolloutManagementTest
findRolloutGroupTargetsWithRsqlParam(org.eclipse.hawkbit.repository.jpa.RolloutManagementTest)  Time elapsed: 0.071 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"MyRollout--000[09]"> but was:<"MyRollout--000[11]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.eclipse.hawkbit.repository.jpa.RolloutManagementTest.findRolloutGroupTargetsWithRsqlParam(RolloutManagementTest.java:1066)

Running org.eclipse.hawkbit.repository.jpa.ReportManagementTest

And then:

[INFO] hawkBit :: Repository :: Test Utilities ............ SUCCESS [  0.206 s]
[INFO] hawkBit :: Repository :: JPA Implementation ........ FAILURE [02:56 min]

Is it a known issue ?

Best regards,
Stefano

**Comment by michahirsch** [comment]
Weird, the CI builds are working
- https://circleci.com/gh/eclipse/hawkbit/1946
- https://hudson.eclipse.org/hawkbit/job/hawkbit-master/

Seems like there is an test-issue maybe order problem or something. 
Could you tell me your mariaDB version ? The CI builds (above) are working only with H2 database but internally we are using MySql for testing.

Cheers,
Michael

**Comment by sbabic** [comment]
On 11/05/2017 15:42, Michael Hirsch wrote:
> Weird, the CI builds are working
> 
>   * https://circleci.com/gh/eclipse/hawkbit/1946
>   * https://hudson.eclipse.org/hawkbit/job/hawkbit-master/
> 
> Seems like there is an test-issue maybe order problem or something.
> Could you tell me your mariaDB version ?

mariadb-server-10.0 on Ubuntu-16.04 (desktop)

But it looks like unrelated to it. I have reset pom.xml to the value on
master, I have no checkout files at all (even the same
application.properties). Build still stops with:

Failed tests:
  RolloutManagementTest.findRolloutGroupTargetsWithRsqlParam:1066
expected:<"MyRollout--000[09]"> but was:<"MyRollout--000[10]">

Tests run: 349, Failures: 1, Errors: 0, Skipped: 0

And then:

[INFO] hawkBit :: Repository :: JPA Implementation ........ FAILURE
[03:07 min]


Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by kaizimmerm** [comment]
This test fails from time to time. I have not figured out yet what the problems is.

**Comment by sbabic** [comment]
Hi Kai,

On 13/05/2017 20:58, Kai Zimmermann wrote:
> This test fails from time to time. I have not figured out yet what the
> problems is.
> 

I pulled again today, I ran a build, no failure ! Surely nothing changed
on my setup, I have no idea why.

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by kaizimmerm** [comment]
It has nothing to do with any changes we did. Its completely random.

**Comment by kaizimmerm** [comment]
I think I got this fixed. Should not happen anymore.
