### ISSUE TITLE
error in ui, any one help me?

### ISSUE THREAD

**Issue by arnold0kang** [eclipse/hawkbit#744]
`2018-09-25 17:31:03.651 ERROR 7964 --- [tp1372422140-14] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI:

org.eclipse.hawkbit.repository.exception.EntityNotFoundException: SoftwareModule with given identifier {1} does not exist.
        at org.eclipse.hawkbit.repository.jpa.JpaArtifactManagement.throwExceptionIfSoftwareModuleDoesNotExist(JpaArtifactManagement.java:210)
        at org.eclipse.hawkbit.repository.jpa.JpaArtifactManagement.findBySoftwareModule(JpaArtifactManagement.java:203)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:122)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy224.findBySoftwareModule(Unknown Source)
        at org.eclipse.hawkbit.ui.artifacts.details.ArtifactBeanQuery.size(ArtifactBeanQuery.java:98)
        at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuery(LazyQueryView.java:402)
        at org.vaadin.addons.lazyquerycontainer.LazyQueryView.getQuerySize(LazyQueryView.java:387)
        at org.vaadin.addons.lazyquerycontainer.LazyQueryView.size(LazyQueryView.java:214)
        at org.vaadin.addons.lazyquerycontainer.LazyQueryContainer.size(LazyQueryContainer.java:181)
        at com.vaadin.ui.AbstractSelect.size(AbstractSelect.java:795)
        at com.vaadin.ui.Table.refreshRenderedCells(Table.java:1707)
        at com.vaadin.ui.Table.attach(Table.java:4241)
        at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:624)
        at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:684)
        at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:624)
        at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:684)
        at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:624)
        at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:684)
        at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:624)
        at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:684)
        at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:587)
        at com.vaadin.ui.AbstractSingleComponentContainer.setContent(AbstractSingleComponentContainer.java:152)
        at com.vaadin.navigator.Navigator$SingleComponentContainerViewDisplay.showView(Navigator.java:229)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:620)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:584)
        at org.eclipse.hawkbit.ui.menu.DashboardMenu$ValoMenuItemButton.lambda$new$a5454672$1(DashboardMenu.java:410)
        at sun.reflect.GeneratedMethodAccessor228.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
        at com.vaadin.ui.Button.fireClick(Button.java:377)
        at com.vaadin.ui.Button$1.click(Button.java:54)
        at sun.reflect.GeneratedMethodAccessor239.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
        at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:148)
        at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:240)
        at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:513)
        at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
        at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
        at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:180)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
        at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
        at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
        at org.atmosphere.container.Jetty9WebSocketHandler.onWebSocketText(Jetty9WebSocketHandler.java:125)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Unknown Source)`

**Comment by laverman** [comment]
Trying my best to help 😉

hawkBit UI stores state information within a session. If entities are being deleted in parallel (e.g. in the context of another user session or via Management API), it might occur, that certain state information is invalid. Moreover, this might be a case, where the UI is not handling this correctly. 

Logging out and in should fix this problem. Can you confirm?

**Comment by arnold0kang** [comment]
hi  Sir, 
  sorry for my late response. I've tried login out. maybe fix this problem, but i'm not sure. for there is another  bug which I posted (timeout) flush all logs . I will check it next time. thanks

**Comment by laverman** [comment]
Shall we keep this issue open, or can we close it and you will re-open it if the issue occurs again?

**Comment by arnold0kang** [comment]
hi Sir, 
   it's up to you , sorry , I'm not a java EE programmer, can't do more.
