### ISSUE TITLE
timeout  on read 

### ISSUE THREAD

**Issue by arnold0kang** [eclipse/hawkbit#745]
`2018-09-25 22:21:52.176 ERROR 13332 --- [uler-1288108586] o.a.container.Jetty9WebSocketHandler     : {}

java.net.SocketTimeoutException: Timeout on Read
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:592)
        at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:168)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:538)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:125)
        at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:166)
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
`
it seems something wrong in web, anyone now why?

**Comment by arnold0kang** [comment]
anyone know?

**Comment by schabdo** [comment]
Indeed it looks like a connectivity issue between UI and hakwBit's update server (backend). Haven't seen this before. May I ask you to share more insight about what you did to get this stack trace?
